[package]
name = "sim"
version = "0.1.0"
authors = ["duysqubix <duys@qubixat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
states = {path = "../../lib/states"}
futures = "0.3"
tokio = {version = "^0.2", features=["full"]}
bytes = "0.5.2"
